service: nodejs-aws-task5-import

frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs14.x
  stage: dev
  region: eu-west-1
  environment:
    CATALOG_ITEMS_QUEUE: !ImportValue catalogItemsQueueUrl

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "s3:ListBucket"
      Resource:
        - "arn:aws:s3:::nodejs-aws-task5"
    - Effect: "Allow"
      Action:
        - "s3:*"
      Resource:
        - "arn:aws:s3:::nodejs-aws-task5/*"
    - Effect: "Allow"
      Action:
        - "sqs:*"
      Resource: !ImportValue catalogItemsQueueArn

resources:
  # API Gateway Errors
  - ${file(resources/api-gateway-errors.yml)}

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          authorizer:
              name: tokenAuthorizer
              arn: "arn:aws:lambda:eu-west-1:369619171521:function:nodejs-aws-task7-basicAuthorizer-dev-basicAuthorizer"
              resultTtlInSeconds: 0
              identitySource: method.request.header.Authorization
              type: token
  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: nodejs-aws-task5
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
          existing: true

